### ISSUE TITLE
feature: Pokemon gets "caught" at end of buffer

### ISSUE THREAD

**Issue by progfolio** [RyanMillerC/poke-mode#4]
Could be neat to conditionally show a pokeball at the end or beginning of the buffer.
Another idea is to have the pokemon faint at the end of buffer, though that would require another image for each pokemon. The pokeball would only require one overall.

**Comment by RyanMillerC** [comment]
Fainting might not work because of the additional image required 🤔. All of the sprites for this project are obtained from PokemonDB.net. I don’t think they provide sprites of fainted Pokémon in the small size we’d need.

Pokeball suggestion could work though if you can find a Pokeball sprite and want to make a PR for it. Should have it as an option to toggle the feature on/off.
